### ISSUE TITLE
Form header shows up as yellow and warning when successful.

### ISSUE THREAD

**Issue by gveater** [VeeamHub/powershell#13]
Same issue as last time just now with the warning and yellow color.  
![veeamcapture](https://cloud.githubusercontent.com/assets/23031506/19658346/9b6e53c6-99f5-11e6-8eac-afeed4fc1a0b.PNG)
The report shows warning with a yellow color even though the job is successful.  The last time I had a warning status on the job was 1 month ago.  Max variable is set to 1.

**Comment by tdewin** [comment]
Hi,

Made a mistake somewhere. I used $lastsession instead of $session. I'm not 100% it will solve it, but it would make sense if it broke the report

Before make another pull request, try with my local branch first:
[https://github.com/tdewin/powershell/tree/e69a404dc7916107d54e28876de077ed21a723cb/BR-MimicReport](https://github.com/tdewin/powershell/tree/e69a404dc7916107d54e28876de077ed21a723cb/BR-MimicReport)

**Comment by gveater** [comment]
It works perfectly, thank you.

**Comment by poulpreben** [comment]
Thanks guys. Merged in #14.
